### ISSUE TITLE
Not working with Sprocket 4

### ISSUE THREAD

**Issue by yamitake** [yasaichi/gakubuchi#10]
### Problem
Rails5.0.1が出たのでSprocket4を使用したら、下記の様なエラーが発生してしまいました。

```
gems/2.3.0/gems/gakubuchi-1.2.3/lib/gakubuchi/engine_registrar.rb:19:in `registered?': undefined method `engines' for #<Sprockets::Environment:0x007ff955b71eb0> (NoMethodError)
```

対応いただけるとありがたいです。

----
### Problem

When I tried using gakubuchi with Sprockets 4, I got the following error: 

```
gems/2.3.0/gems/gakubuchi-1.2.3/lib/gakubuchi/engine_registrar.rb:19:in `registered?': undefined method `engines' for #<Sprockets::Environment:0x007ff955b71eb0> (NoMethodError)
```

Would you deal with it?
(translated by @yasaichi)

**Comment by yasaichi** [comment]
Sorry for the inconvenience, @yamitake.
Currently we're working to resolve it on [this branch]( https://github.com/yasaichi/gakubuchi/tree/support-sprockets4).
So could you wait until it is merged into master? :bow:

**Comment by yasaichi** [comment]
Close this because gakubuchi has supported Sprockets 4 since v1.4.0.
