### ISSUE TITLE
Can't use helper methods

### ISSUE THREAD

**Issue by tsuwatch** [yasaichi/gakubuchi#21]
In Rails 5.0.1, sprockets-rails 3.2.0, sprockets 3.7.1 etc, for example
```sh
undefined method `stylesheet_link_tag' for #<Object:0x007f147740c5d0>
```

In Rails 4.2.7.1, sprockets-rails 3.2.0, sprockets 3.7.1 is maybe ok!

**Comment by yasaichi** [comment]
@tsuwatch
Thank you for submitting your bug report :bow:
I tried to reproduced the bug with [this repo](https://github.com/yasaichi/gakubuchi_demo), but I couldn't do that.
So could you please give me further information on your app?

**Comment by tsuwatch** [comment]
Thanks.
When using `slim-rails` in that repo, maybe reproduce.

**Comment by yasaichi** [comment]
@tsuwatch 
Ah, it is caused by the buggy code of slim-rails 3.1.1 and 3.2.2 😢 
So could you try either of the followings?

* Downgrade the version  to 3.1.0 or former
* Use the master, specifically https://github.com/slim-template/slim-rails/commit/2f70a44c518e4a6f083aa5a8cf914510c99f23de or later

**Comment by tsuwatch** [comment]
Ah, I see.
I resolved this bug.
Thank you for your help!
